#!/usr/bin/env bash
# Make `terraform apply` survive a rebuild that follows a destroy.
#
# THE PROBLEM
#
# destroy.sh does not really delete the Secrets Manager secrets — nothing can. A delete
# schedules them, with a recovery window (30 days here, the provider default). For the
# whole of that window the NAME stays taken, and CreateSecret refuses it:
#
#   InvalidRequestException: You can't create this secret because a secret with this
#   name is already scheduled for deletion.
#
# Terraform has no state for them after a destroy, so it plans a create, and every
# rebuild inside 30 days fails on all six at once. The teardown "succeeded" and left a
# landmine for the next deploy — the same shape as the finalizer deadlock destroy.sh
# already guards against.
#
# THE FIX, AND WHY IT IS NOT "JUST FORCE-DELETE THEM"
#
# --force-delete-without-recovery would make the name reusable immediately and throw
# away the VALUES. Three of these secrets are hand-entered — the Slack webhook, the
# Grafana Cloud token, the Docker Hub credentials — and nothing in git can regenerate
# them. So: restore, then import, which keeps both the name and the contents.
#
# Importing the VERSIONS matters as much as importing the secrets. `ignore_changes =
# [secret_string]` only protects an UPDATE to a resource Terraform already tracks. A
# version that is absent from state gets CREATED from the variable, and the variables
# for the hand-entered ones are empty — so an import of the container alone would
# quietly overwrite a real webhook with "REPLACE_ME" and blank the tokens. Silently,
# because a secret's value never appears in a plan diff.
#
# Safe to run every time: it restores only what is actually pending deletion and
# imports only what is actually missing from state.
#
# Run from infra/terraform/ with terraform already initialised.

set -euo pipefail

echo "==> Checking for secrets left in the deletion recovery window"

# resource address : secret name
SECRETS="
django_secret_key:helpdesk/django-secret-key
cors_allowed_origins:helpdesk/cors-allowed-origins
dockerhub_credentials:helpdesk/dockerhub-credentials
grafana_admin_password:helpdesk/grafana-admin-password
slack_webhook_url:helpdesk/slack-webhook-url
grafana_cloud_credentials:helpdesk/grafana-cloud-credentials
"

# Only these three carry hand-entered values, so only these three need their VERSION
# imported to avoid being recreated blank. The other three are generated by Terraform
# (random_password) or derived from the EIP, and are safe to let it rewrite.
PROTECTED="slack_webhook_url grafana_cloud_credentials dockerhub_credentials"

RESTORED=0
IMPORTED=0

STATE="$(terraform state list 2>/dev/null || true)"

for pair in $SECRETS; do
  res="${pair%%:*}"
  name="${pair##*:}"

  # Is it pending deletion? A secret that does not exist at all returns nothing here,
  # which is the clean-account case — leave it for Terraform to create normally.
  deleted=$(aws secretsmanager describe-secret --secret-id "$name" \
    --query 'DeletedDate' --output text 2>/dev/null || echo "")

  if [ -n "$deleted" ] && [ "$deleted" != "None" ]; then
    echo "    restoring ${name} (was scheduled for deletion)"
    aws secretsmanager restore-secret --secret-id "$name" >/dev/null
    RESTORED=$((RESTORED + 1))
  fi

  # Exists in AWS but not in state -> import, or Terraform will try to create it.
  if aws secretsmanager describe-secret --secret-id "$name" >/dev/null 2>&1; then
    if ! printf '%s\n' "$STATE" | grep -qx "aws_secretsmanager_secret.${res}"; then
      echo "    importing aws_secretsmanager_secret.${res}"
      terraform import -input=false -no-color "aws_secretsmanager_secret.${res}" "$name" >/dev/null 2>&1 \
        && IMPORTED=$((IMPORTED + 1)) \
        || echo "      WARNING: import failed for ${res}; apply may try to recreate it." >&2
    fi

    case " $PROTECTED " in
      *" $res "*)
        if ! printf '%s\n' "$STATE" | grep -qx "aws_secretsmanager_secret_version.${res}"; then
          vid=$(aws secretsmanager list-secret-version-ids --secret-id "$name" \
            --query "Versions[?contains(VersionStages,'AWSCURRENT')].VersionId|[0]" \
            --output text 2>/dev/null || echo "")
          if [ -n "$vid" ] && [ "$vid" != "None" ]; then
            echo "    importing aws_secretsmanager_secret_version.${res} (preserves the hand-entered value)"
            terraform import -input=false -no-color \
              "aws_secretsmanager_secret_version.${res}" "${name}|${vid}" >/dev/null 2>&1 \
              && IMPORTED=$((IMPORTED + 1)) \
              || echo "      WARNING: version import failed for ${res} — apply may blank it." >&2
          fi
        fi
        ;;
    esac
  fi
done

if [ "$RESTORED" -eq 0 ] && [ "$IMPORTED" -eq 0 ]; then
  echo "    nothing pending — no secrets to restore or import"
else
  echo "    restored ${RESTORED}, imported ${IMPORTED}"
fi
